# permissions for end users to edit namespacesetups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: namespacesetup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: namespace-default-workload-operator
    app.kubernetes.io/part-of: namespace-default-workload-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespacesetup-editor-role
rules:
- apiGroups:
  - resource.muntashirislam.com
  resources:
  - namespacesetups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.muntashirislam.com
  resources:
  - namespacesetups/status
  verbs:
  - get
